name: Build

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: version
        run: echo "build_version=$(cat VERSION.md)" >> $GITHUB_ENV
        id: version
      - run: pnpm install
      - name: Publish release
        run: pnpm run build --if-present
      # no tests for now...
      #    - run: pnpm test

      # publish
      - name: Publish
        run: cd ./.output/ && tar -czf veil.tools-${{ env.build_version }}.tar.gz *
      - uses: actions/upload-artifact@v4
        with:
          name: veil.tools-${{ env.build_version }}
          path: ./.output/veil.tools-${{ env.build_version }}.tar.gz