name: Create release

on:
  push:
    tags:    
      - "release/**"

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: bypass npm bug
      run: rm package-lock.json
    - name: version
      run: echo "build_version=$(cat VERSION.md)" >> $GITHUB_ENV
      id: version
    - run: npm install
    - name: Publish release
      run: npm run build --if-present
    # no tests for now...
#    - run: npm test

    # publish
    - name: Publish
      run: cd ./.output/ && tar -czf veil.tools-${{ env.build_version }}.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: veil.tools-${{ env.build_version }}
        path: ./.output/veil.tools-${{ env.build_version }}.tar.gz

  publish-release:
    needs: [build-website]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: version
        run: echo "build_version=$(cat VERSION.md)" >> $GITHUB_ENV
        id: version

      - uses: actions/download-artifact@master
        with:
          name: veil.tools-${{ env.build_version }}
          path: artifacts/veil.tools-${{ env.build_version }}.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{ env.build_version }}
          files: |
            LICENSE
            README.md
            VERSION.md
            ./artifacts/**